/*
* DISCLAIMER: THIS FILE IS GENERATED BY THE code_gen/gen_data_header.py SCRIPT.
* ANY CHANGES MADE TO THIS FILE WILL BE OVRITTEN!
*/

/**
* @ingroup     silenos
* @{
* 
* @file
* @brief generated sensor config header.
* 
* @author      Timon Rupelt <me@ruptim.dev>
* @}
*/

#pragma once

#include "sensors.h"

#ifdef __cplusplus
extern C {
#endif

/* Location of the sensors defined in the config file. */
#define SENSOR_CONFIG_LOCATION "polder40/gate14"

/* Polder number of the location. */
#define SENSOR_CONFIG_LOCATION_POLDER 40

/* Gate number of the location. */
#define SENSOR_CONFIG_LOCATION_GATE 14

/* Number of physical sensors connected. */
#define NUM_SENSORS 3

/* Number of contacts (physical connections) (some sensors have multiple contacts e.g. reed sensors) */
#define NUM_UNIQUE_SENSOR_VALUES 3

/* Configuration in which the sensors are to be interpreted. */
#define ACTIVE_MULTI_SENSOR_MODE MAJORITY_SEQUENCE

/* holds all callback arguments for all sensors */
extern alarm_cb_args_t alarm_cb_args[NUM_UNIQUE_SENSOR_VALUES];

/* IDs for all contacts per sensor to use with parameters and identification in messages. */

#define SENSOR_1_ID 0
#define SENSOR_1_REED_NO_ID 0

#define SENSOR_2_ID 1
#define SENSOR_2_REED_NO_ID 1

#define SENSOR_3_ID 2
#define SENSOR_3_REED_NO_ID 2

/*  The number of maximum bytes needed for all sensor values. */
#define SENSORS_MAX_VALUE_BYTES_NEEDED 3

extern sensor_base_type_t registered_sensors[3];
extern sensor_base_params_t registered_sensors_params[3];


/**
* @brief  Intiatialize all configured sensors with their corresponding drivers and parameters.
* 
* @return 0 if all drivers where intialized correctly, -1 otherwise.
*/
int init_sensors(kernel_pid_t receive_pid);


#ifdef __cplusplus
}
#endif
