/*
* DISCLAIMER: THIS FILE IS GENERATED BY THE code_gen/gen_data_header.py SCRIPT.
* ANY CHANGES MADE TO THIS FILE WILL BE OVRITTEN!
*/

/**
* @ingroup     silenos
* @{
* 
* @file
* @brief generated sensor config header.
* 
* @author      Timon Rupelt <me@ruptim.dev>
* @}
*/

#ifndef SENSOR_CONFIG_H_
#define SENSOR_CONFIG_H_

#include "sensors.h"

#ifdef __cplusplus
extern C {
#endif

/* Number of physical sensors connected. */
#define NUM_SENSORS 2

/* Number of contacts (physical connections) (some sensors have multiple contacts e.g. reed sensors) */
#define NUM_UNIQUE_SENSOR_VALUES 4

static alarm_cb_args_t alarm_cb_args[NUM_UNIQUE_SENSOR_VALUES];

/* IDs for all contacts per sensor to use with parameters and identification in messages. */

#define SENSOR_1_REED_NC_ID 0
#define SENSOR_1_REED_NO_ID 1

#define SENSOR_2_REED_NC_ID 2
#define SENSOR_2_REED_NO_ID 3

sensor_base_type_t registered_sensors[2];
sensor_base_params_t registered_sensors_params[2];

/**
* @brief  Intiatialize all configured sensors with their corresponding drivers and parameters.
* 
* @return 0 if all drivers where intialized correctly, -1 otherwise.
*/
int init_sensors(void);
#ifdef __cplusplus
}
#endif

#endif // SENSOR_CONFIG_H_