
# drivers
USEMODULE += dwax509m183x0
USEMODULE += reed_sensor_driver
USEMODULE += ztimer_sec
USEMODULE += ztimer_msec


# interfaces
USEMODULE += netdev_default
USEMODULE += auto_init_gnrc_netif

# GNRC modules to build and receive packets
USEMODULE += gnrc_pktbuf
USEMODULE += gnrc_netif_hdr
USEMODULE += gnrc_netapi
USEMODULE += gnrc_netreg
USEMODULE += gnrc_neterr

# Include OD to print received packets
USEMODULE += od
# Add support for GNRC LoRaWAN
USEMODULE += gnrc_lorawan



USEMODULE += sx127x


USEPKG += tinycbor
